stages:
  - deploy

deploy:
  image: node:8
  stage: deploy
  environment: production
  script:
    - npm install -g firebase-tools
    - firebase -V
    - firebase deploy --token "$FIREBASE_TOKEN" -P <my-firebase-project>
  only:
    - master